name: Cppcheck Analysis
on: [push]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cppcheck
        run: sudo apt-get install cppcheck
      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive Arm.cpp
